# Generated by Django 5.2.4 on 2025-09-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=50)),
                ('stipend', models.CharField(max_length=50)),
                ('match_reason', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('apply_link', models.URLField()),
                ('skills', models.CharField(help_text='Comma-separated skills', max_length=255)),
                ('interests', models.CharField(help_text='Comma-separated interests', max_length=255)),
            ],
        ),
    ]
