# Generated by Django 5.2.4 on 2025-09-06 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship',
            name='match_reason',
        ),
    ]
